import { Alert, ASHAWeeklyReport, CaseRecord, DashboardStats, ReportData } from "../types";

export const WEEKLY_CASES_DATA = [
    { week: 'Wk 1', cases: 12 },
    { week: 'Wk 2', cases: 19 },
    { week: 'Wk 3', cases: 15 },
    { week: 'Wk 4', cases: 28 },
    { week: 'Wk 5', cases: 45 },
    { week: 'Wk 6', cases: 32 },
];

export const RAINFALL_VS_CASES_DATA = [
    { week: 'Wk 1', rainfall: 120, cases: 12 },
    { week: 'Wk 2', rainfall: 150, cases: 19 },
    { week: 'Wk 3', rainfall: 180, cases: 15 },
    { week: 'Wk 4', rainfall: 220, cases: 28 },
    { week: 'Wk 5', rainfall: 300, cases: 45 },
    { week: 'Wk 6', rainfall: 250, cases: 32 },
];

export const DASHBOARD_STATS: DashboardStats = {
    totalCases: 151,
    rainfallAverage: 203,
    waterQualityStatus: "Moderate",
    currentRiskLevel: "High"
};

export const ALERTS: Alert[] = [
    {
        id: "1",
        district: "Dhubri",
        date: "2024-02-15",
        riskLevel: "High",
        message: "Critical rainfall levels detected. High probability of water contamination."
    },
    {
        id: "2",
        district: "Barpeta",
        date: "2024-02-14",
        riskLevel: "Moderate",
        message: "Rising diarrhea cases reported near river banks."
    },
    {
        id: "3",
        district: "Kamrup",
        date: "2024-02-12",
        riskLevel: "Low",
        message: "Water quality parameters within safe limits."
    },
    {
        id: "4",
        district: "Nalbari",
        date: "2024-02-10",
        riskLevel: "High",
        message: "Bacterial count exceeds safety threshold in community wells."
    },
    {
        id: "5",
        district: "Sambalpur",
        date: "2024-06-15",
        riskLevel: "High",
        message: "Heavy rainfall causing increased turbidity and Cholera case spikes in Burla and Modipara."
    },
    {
        id: "6",
        district: "Sambalpur",
        date: "2026-03-20",
        riskLevel: "High",
        message: "Cluster of acute diarrhea reported from Ainthapali wards after pipe-line leakage."
    },
    {
        id: "7",
        district: "Sambalpur",
        date: "2026-03-18",
        riskLevel: "Moderate",
        message: "Rising Typhoid trend observed in Budharaja and nearby settlements; chlorination advised."
    },
    {
        id: "8",
        district: "Sambalpur",
        date: "2026-03-17",
        riskLevel: "Moderate",
        message: "Water samples near Hirakud fringe show elevated BOD levels after recent rainfall."
    },
    {
        id: "9",
        district: "Sambalpur",
        date: "2026-03-14",
        riskLevel: "Low",
        message: "Post-cleaning surveillance in Bareipali indicates improving potable water quality."
    },
    {
        id: "10",
        district: "Sambalpur",
        date: "2026-03-12",
        riskLevel: "High",
        message: "Emergency advisory issued for Modipara due to repeated gastrointestinal outbreaks."
    },
    {
        id: "11",
        district: "Sambalpur",
        date: "2026-03-11",
        riskLevel: "Moderate",
        message: "Ainthapali ward handpump samples show elevated coliform counts; residents advised to boil water."
    },
    {
        id: "12",
        district: "Sambalpur",
        date: "2026-03-10",
        riskLevel: "High",
        message: "Burla low-lying settlements report spike in diarrhea following drainage overflow."
    },
    {
        id: "13",
        district: "Sambalpur",
        date: "2026-03-09",
        riskLevel: "Moderate",
        message: "Khetrajpur school cluster reports fever and stomach infection trend; chlorination initiated."
    },
    {
        id: "14",
        district: "Sambalpur",
        date: "2026-03-08",
        riskLevel: "Low",
        message: "Hirakud plant-side water quality improving after pipeline flushing and tank cleaning."
    },
    {
        id: "15",
        district: "Sambalpur",
        date: "2026-03-07",
        riskLevel: "Moderate",
        message: "Dhanupali locality reports intermittent muddy tap water and mild dysentery cases."
    },
    {
        id: "16",
        district: "Sambalpur",
        date: "2026-03-06",
        riskLevel: "High",
        message: "Budharaja market area flagged for acute gastroenteritis cluster in households using borewell water."
    },
    {
        id: "17",
        district: "Sambalpur",
        date: "2026-03-05",
        riskLevel: "Moderate",
        message: "Sakhipara and nearby lanes show rising typhoid trend; door-to-door awareness drive launched."
    },
    {
        id: "18",
        district: "Sambalpur",
        date: "2026-03-04",
        riskLevel: "Low",
        message: "Farm Road peripheral colonies now within safe pH and BOD range after temporary interventions."
    }
];

export const DISTRICTS = [
    "Sambalpur", "Dhubri", "Kokrajhar", "Barpeta", "Nalbari", "Baksa",
    "Kamrup", "Darrang", "Sonitpur", "Lakhimpur", "Dhemaji"
];

export const ASHA_WEEKLY_REPORTS: ASHAWeeklyReport[] = [
    {
        id: "wr-1",
        weekNumber: 9,
        year: 2026,
        district: "Sambalpur",
        locationName: "Burla",
        diarrheaCases: 11,
        choleraCases: 2,
        typhoidCases: 4,
        rainfall: 142,
        waterQuality: "Moderate",
        symptoms: "Loose motion, mild dehydration",
        submittedAt: "2026-03-03T10:10:00.000Z",
        riskLevel: "High",
    },
    {
        id: "wr-2",
        weekNumber: 10,
        year: 2026,
        district: "Sambalpur",
        locationName: "Ainthapali",
        diarrheaCases: 9,
        choleraCases: 1,
        typhoidCases: 3,
        rainfall: 130,
        waterQuality: "Moderate",
        symptoms: "Fever and vomiting in children",
        submittedAt: "2026-03-10T09:20:00.000Z",
        riskLevel: "Moderate",
    },
    {
        id: "wr-3",
        weekNumber: 11,
        year: 2026,
        district: "Sambalpur",
        locationName: "Modipara",
        diarrheaCases: 6,
        choleraCases: 0,
        typhoidCases: 2,
        rainfall: 118,
        waterQuality: "Good",
        symptoms: "Mostly mild gastroenteritis",
        submittedAt: "2026-03-17T12:40:00.000Z",
        riskLevel: "Low",
    },
];

export const CASE_RECORDS: CaseRecord[] = [
    {
        id: "cr-1",
        weekNumber: 11,
        year: 2026,
        district: "Sambalpur",
        locationName: "Burla",
        diseaseType: "Diarrhea",
        casesReported: 17,
        riskLevel: "High",
        reportedBy: "ASHA - Burla",
        reportedAt: "2026-03-18T07:20:00.000Z",
    },
    {
        id: "cr-2",
        weekNumber: 11,
        year: 2026,
        district: "Sambalpur",
        locationName: "Ainthapali",
        diseaseType: "Typhoid",
        casesReported: 8,
        riskLevel: "Moderate",
        reportedBy: "ASHA - Ainthapali",
        reportedAt: "2026-03-18T09:00:00.000Z",
    },
    {
        id: "cr-3",
        weekNumber: 11,
        year: 2026,
        district: "Sambalpur",
        locationName: "Modipara",
        diseaseType: "Cholera",
        casesReported: 5,
        riskLevel: "High",
        reportedBy: "ASHA - Modipara",
        reportedAt: "2026-03-19T11:10:00.000Z",
    },
    {
        id: "cr-4",
        weekNumber: 10,
        year: 2026,
        district: "Sambalpur",
        locationName: "Remed",
        diseaseType: "Dysentery",
        casesReported: 4,
        riskLevel: "Low",
        reportedBy: "PHC Remed",
        reportedAt: "2026-03-12T08:40:00.000Z",
    },
    {
        id: "cr-5",
        weekNumber: 10,
        year: 2026,
        district: "Sambalpur",
        locationName: "Budharaja",
        diseaseType: "Hepatitis A",
        casesReported: 3,
        riskLevel: "Moderate",
        reportedBy: "District Hospital",
        reportedAt: "2026-03-13T14:20:00.000Z",
    },
    {
        id: "cr-6",
        weekNumber: 12,
        year: 2026,
        district: "Sambalpur",
        locationName: "Bareipali",
        diseaseType: "Diarrhea",
        casesReported: 13,
        riskLevel: "High",
        reportedBy: "ASHA - Bareipali",
        reportedAt: "2026-03-21T08:25:00.000Z",
    },
    {
        id: "cr-7",
        weekNumber: 12,
        year: 2026,
        district: "Sambalpur",
        locationName: "Khetrajpur",
        diseaseType: "Typhoid",
        casesReported: 9,
        riskLevel: "Moderate",
        reportedBy: "Urban Health Unit",
        reportedAt: "2026-03-21T10:05:00.000Z",
    },
    {
        id: "cr-8",
        weekNumber: 12,
        year: 2026,
        district: "Sambalpur",
        locationName: "Hirakud",
        diseaseType: "Cholera",
        casesReported: 6,
        riskLevel: "High",
        reportedBy: "PHC Hirakud",
        reportedAt: "2026-03-22T09:30:00.000Z",
    },
    {
        id: "cr-9",
        weekNumber: 12,
        year: 2026,
        district: "Sambalpur",
        locationName: "Dhanupali",
        diseaseType: "Dysentery",
        casesReported: 7,
        riskLevel: "Moderate",
        reportedBy: "ASHA - Dhanupali",
        reportedAt: "2026-03-22T12:40:00.000Z",
    },
    {
        id: "cr-10",
        weekNumber: 13,
        year: 2026,
        district: "Sambalpur",
        locationName: "Burla",
        diseaseType: "Hepatitis A",
        casesReported: 5,
        riskLevel: "Moderate",
        reportedBy: "VSS Medical Unit",
        reportedAt: "2026-03-28T11:15:00.000Z",
    },
    {
        id: "cr-11",
        weekNumber: 13,
        year: 2026,
        district: "Sambalpur",
        locationName: "Ainthapali",
        diseaseType: "Diarrhea",
        casesReported: 15,
        riskLevel: "High",
        reportedBy: "ASHA - Ainthapali",
        reportedAt: "2026-03-28T13:05:00.000Z",
    },
    {
        id: "cr-12",
        weekNumber: 13,
        year: 2026,
        district: "Sambalpur",
        locationName: "Budharaja",
        diseaseType: "Typhoid",
        casesReported: 6,
        riskLevel: "Low",
        reportedBy: "District Surveillance Team",
        reportedAt: "2026-03-29T09:45:00.000Z",
    },
    {
        id: "cr-13",
        weekNumber: 13,
        year: 2026,
        district: "Sambalpur",
        locationName: "Sakhipara",
        diseaseType: "Diarrhea",
        casesReported: 10,
        riskLevel: "Moderate",
        reportedBy: "ASHA - Sakhipara",
        reportedAt: "2026-03-29T12:20:00.000Z",
    },
    {
        id: "cr-14",
        weekNumber: 13,
        year: 2026,
        district: "Sambalpur",
        locationName: "Motijharan",
        diseaseType: "Dysentery",
        casesReported: 4,
        riskLevel: "Low",
        reportedBy: "Urban Health Unit",
        reportedAt: "2026-03-29T15:05:00.000Z",
    },
    {
        id: "cr-15",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Ainthapali",
        diseaseType: "Diarrhea",
        casesReported: 16,
        riskLevel: "High",
        reportedBy: "ASHA - Ainthapali",
        reportedAt: "2026-04-02T08:35:00.000Z",
    },
    {
        id: "cr-16",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Burla",
        diseaseType: "Typhoid",
        casesReported: 11,
        riskLevel: "Moderate",
        reportedBy: "VSS Medical Unit",
        reportedAt: "2026-04-02T10:15:00.000Z",
    },
    {
        id: "cr-17",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Hirakud",
        diseaseType: "Cholera",
        casesReported: 7,
        riskLevel: "High",
        reportedBy: "PHC Hirakud",
        reportedAt: "2026-04-02T11:10:00.000Z",
    },
    {
        id: "cr-18",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Dhanupali",
        diseaseType: "Hepatitis A",
        casesReported: 6,
        riskLevel: "Moderate",
        reportedBy: "District Hospital",
        reportedAt: "2026-04-03T09:45:00.000Z",
    },
    {
        id: "cr-19",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Budharaja",
        diseaseType: "Diarrhea",
        casesReported: 12,
        riskLevel: "High",
        reportedBy: "ASHA - Budharaja",
        reportedAt: "2026-04-03T13:00:00.000Z",
    },
    {
        id: "cr-20",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Khetrajpur",
        diseaseType: "Typhoid",
        casesReported: 8,
        riskLevel: "Moderate",
        reportedBy: "Urban Surveillance Cell",
        reportedAt: "2026-04-03T16:20:00.000Z",
    },
    {
        id: "cr-21",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Farm Road",
        diseaseType: "Dysentery",
        casesReported: 5,
        riskLevel: "Low",
        reportedBy: "ASHA - Farm Road",
        reportedAt: "2026-04-04T10:25:00.000Z",
    },
    {
        id: "cr-22",
        weekNumber: 14,
        year: 2026,
        district: "Sambalpur",
        locationName: "Bareipali",
        diseaseType: "Cholera",
        casesReported: 9,
        riskLevel: "High",
        reportedBy: "PHC Bareipali",
        reportedAt: "2026-04-04T12:50:00.000Z",
    },
];
